### ISSUE TITLE
Multi drive support

### ISSUE THREAD

**Issue by ivop** [davidgiven/cpm65#151] opened 2024-08-25 18:46 UTC
Hi,

I tried adding a second drive to the Atari port (https://github.com/ivop/cpm65/tree/atari-multi-drive) but it does not seem to work as expected:

![atari000](https://github.com/user-attachments/assets/a029b1f4-2686-4141-906b-60361c7625fc)
![atari001](https://github.com/user-attachments/assets/8ba61887-fa53-4bc3-befe-bd9857c24def)

Directory of A: works normally. I switch to B: and then the directory listing is not correct. CTRL-C and the DIR, still wrong. But DIR B: suddenly shows the correct directory. Any idea what's going on here?

Regards,
Ivo

Edit: I looked at the nano6502 port and as far as I can see I did exactly what they did, i.e. return a separate dph for each drive.

**Comment by davidgiven** [comment] 2024-08-25 19:41
A lot of these issues got fixed in #113, but there's clearly something else wrong.

The symptoms look weird. If you look at the first sector of the directory of B:, are the entries for ATBASIC.COM and ATBASIC.TXT next to each other in the same sector? If so, then it looks like the last-visible-item variable in the BDOS is being somehow set to 1, which it shouldn't be. It's an optimisation to allow unused sectors of the directory to be skipped. It's supposed to be determined when the drive is logged on.

**Comment by ivop** [comment] 2024-08-26 01:53
More funny behaviour :)

![atari000](https://github.com/user-attachments/assets/8d42d5e9-50f8-4371-bcf1-ece1050b1b1e)
![atari001](https://github.com/user-attachments/assets/06e8d7d0-d113-45ca-999a-8d2e42949cdc)

I found out that when I type B: this code does not seem to work correctly:
```
    ; Decide if the drive was already logged in.

    lda login_vector+0
    ldx login_vector+1
    ldy active_drive
    jsr shiftr              ; flag at bottom of temp+0

    ror temp+0
    zif_cs
        jmp .    ; debug, endless loop
        rts
    zendif
```

The first time it should not take the zif_cs and continue after zendif because the drive was not logged in yet. But it thinks it does.

**Comment by ivop** [comment] 2024-08-26 02:15
Found it!

```
zproc internal_LOGINDRIVE
    ; Select the drive.

    sta active_drive          ; <----- MISSING
    jsr select_active_drive

    ; Decide if the drive was already logged in.
```

select_active_drive starts with lda active_drive, which is 0.

I have put sta active_drive within internal_LOGINDRIVE because elsewhere it is called with A set to what has to become the active drive.

![atari002](https://github.com/user-attachments/assets/92c735a0-58b0-4ddb-8f1e-4f08815cbda4)
![atari003](https://github.com/user-attachments/assets/e801a026-795b-402f-a34c-dc0e6234f96c)

**Comment by venomix666** [comment] 2024-08-26 05:18
Fantastic! This bug was driving me crazy when I tried to find the cause for it (see #113), I'm really happy to see it fixed.

**Comment by ivop** [comment] 2024-08-26 17:07
Thanks. There's still something fishy going on though.

![atari000](https://github.com/user-attachments/assets/52692c14-69f0-4e8b-b036-e25957306d32)
![atari001](https://github.com/user-attachments/assets/ddc21d2b-dbe3-4373-b117-957a36caa772)

Opening a file on a drive that has not been logged in yet does not work. I'll look into it later tonight.

**Comment by ivop** [comment] 2024-08-26 18:02
Think I found it. OPENFILE and CREATEFILE call convert_user_fcb. convert_user_fcb stores the drive number to active_drive and calls select_active_drive, which does not log in the drive. Changing that to internal_LOGINDRIVE (which calls select_active_drive, too) seems to fix this:

```
--- a/src/bdos/filesystem.S
+++ b/src/bdos/filesystem.S
@@ -243,13 +243,12 @@ zproc convert_user_fcb
     zif_mi
         ldx current_drive       ; override with current drive
     zendif
-    txa
-    sta active_drive            ; set the active drive
 
     lda current_user
     sta (param), y              ; update FCB
 
-    jmp select_active_drive
+    txa
+    jmp internal_LOGINDRIVE
 zendproc
```

I'll send a pull request after diner.

**Comment by ivop** [comment] 2024-08-27 00:11
Okay, that turned out to be the wrong fix, even though the problem description is right (i.e. all file related bdos_* functions call convert_user_fcb which then uses an active drive that is not logged in yet).

Another thing I noticed is this:

![atari000](https://github.com/user-attachments/assets/b1fdb822-355c-4aa9-beb8-1d7a6067e06c)

DIR B: silently changes the selected drive to B, but CCP does not update its prompt (global drive variable). Not even when I press enter. Only after CTRL-C does it notice it's no longer on A:. Same happens with TYPE B:somefile.txt

Perhaps CCP should call bdos_SELECTDSK with the drive variable as a parameter in the main loop? This automatically returns to what was the current drive before when calling an external application, too. @davidgiven ?

**Comment by davidgiven** [comment] 2024-08-27 09:10
`dir b:` shouldn't change the active drive.

From looking at the code, I think the BDOS isn't distinguishing between selecting the drive temporarily when working on an FCB on the non-current drive, and a call to LOGINDRIVE. I think BEGINSYS/ENDSYS need to store the old value of `current_drive` and restore it after the system call is done with, like the FCB drive is.

**Comment by ivop** [comment] 2024-08-27 16:15
In ccp.S, entry_DIR explicitly calls bdos_SELECTDISK. If I remove that, BDOS automatically uses the drive that's set in userfcb and then DIR B: does not change the active drive in CCP.  Transient commands, like stat, ls and dinfo, still change the active drive, but I suppose that's because they all call bdos_SELECTDISK, too, instead of relying on BDOS accessing the correct drive that is set in the passed fcb.

**Comment by davidgiven** [comment] 2024-10-29 19:48
Yup, I've just run into this myself on a new port. Investigating.

**Closed** 2024-10-30 22:23 UTC
